openapi: 3.0.3
info:
  title: Trip Planner - REST API
  description: >-
    API specification for trip planner API server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:8080
tags:
  - name: trip-planner
    description: Trip planner API
paths:
  /version:
    summary: Trip planner API version
    get:
      summary: Trip planner API version
      operationId: TripPlannerAppVersion
      tags:
        - trip-planner
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KeyValue"

components:
  schemas:
    KeyValue:
      type: object
      properties:
        version:
          type: string
          example: "1.0.0"
