apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig

outbound:
  serviceReferences:
  - name: choreo:///wisdomtech/plnx/jlkrhh/proxy/v1.0/PUBLIC
    connectionConfig: 01eee778-01f5-1298-aac8-7483f5a81ae2
    env:
    - from: ServiceURL
      to: SERVICE_URL
    - from: ConsumerKey
      to: CONSUMER_KEY
    - from: ConsumerSecret
      to: CONSUMER_SECRET
    - from: TokenURL
      to: TOKEN_URL
